## Classification using Multilayer Perceptron

```{r}
# DAL ToolBox
# version 1.1.737



#loading DAL
library(daltoolbox) 
```

```{r}
iris <- datasets::iris
head(iris)
```

```{r}
#extracting the levels for the dataset
slevels <- levels(iris$Species)
slevels
```

```{r}
#for performance issues, you can use matrix instead of data.frame (uncomment next line to test)
iris <- cbind(as.matrix(iris[,1:4]), Species=iris$Species)
```

## Building samples (training and testing)

```{r}
# preparing dataset for random sampling
set.seed(1)
sr <- sample_random()
sr <- train_test(sr, iris)
iris_train <- sr$train
iris_test <- sr$test
```

```{r}
tbl <- rbind(table(iris[,"Species"]), 
             table(iris_train[,"Species"]), 
             table(iris_test[,"Species"]))
rownames(tbl) <- c("dataset", "training", "test")
head(tbl)
```

### Model training

```{r}
model <- cla_mlp("Species", slevels, size=3,decay=0.03)
model <- fit(model, iris_train)
train_prediction <- predict(model, iris_train)
```

### Model adjustment

```{r}
iris_train_predictand <- adjust_class_label(iris_train[,"Species"])
train_eval <- evaluate(model, iris_train_predictand, train_prediction)
print(train_eval$metrics)
```

### Model testing

```{r}
# Test  
test_prediction <- predict(model, iris_test)
  
iris_test_predictand <- adjust_class_label(iris_test[,"Species"])
test_eval <- evaluate(model, iris_test_predictand, test_prediction)
print(test_eval$metrics)
```

