## Tune Regression 

```{r}
# DAL ToolBox
# version 1.2.707



#loading DAL
library(daltoolbox) 
```

### Dataset for classification

```{r}
iris <- datasets::iris
head(iris)

#extracting the levels for the dataset
slevels <- levels(iris$Species)
slevels
```

## Building samples (training and testing)

```{r}
# preparing dataset for random sampling
set.seed(1)
sr <- sample_random()
sr <- train_test(sr, iris)
iris_train <- sr$train
iris_test <- sr$test

tbl <- rbind(table(iris[,"Species"]),
             table(iris_train[,"Species"]),
             table(iris_test[,"Species"]))
rownames(tbl) <- c("dataset", "training", "test")
head(tbl)
```

### Training

```{r}
tune <- cla_tune(cla_svm("Species", slevels))
ranges <- list(epsilon=seq(0,1,0.2), cost=seq(20,100,20), kernel = c("linear", "radial", "polynomial", "sigmoid"))

model <- fit(tune, iris_train, ranges)
```

### Model adjustment

```{r}
train_prediction <- predict(model, iris_train)

iris_train_predictand <- adjust_class_label(iris_train[,"Species"])
train_eval <- evaluate(model, iris_train_predictand, train_prediction)
print(train_eval$metrics)
```

### Test

```{r}
# Test
test_prediction <- predict(model, iris_test)

iris_test_predictand <- adjust_class_label(iris_test[,"Species"])

#Avaliação #setosa
test_eval <- evaluate(model, iris_test_predictand, test_prediction)
print(test_eval$metrics)

#Avaliação #versicolor
test_eval <- evaluate(model, iris_test_predictand, test_prediction, ref=2)
print(test_eval$metrics)

#Avaliação #virginica
test_eval <- evaluate(model, iris_test_predictand, test_prediction, ref=3)
print(test_eval$metrics)
```

### Options for other models

```{r}
#knn
ranges <- list(k=1:20)

#mlp
ranges <- list(size=1:10, decay=seq(0, 1, 0.1))

#rf
ranges <- list(mtry=1:3, ntree=1:10)
```

