Sobre o método
- `cla_knn`: classificador k-Nearest Neighbors. Classifica pela maioria entre os k vizinhos mais próximos no espaço de atributos.
- Parâmetro principal: `k` (número de vizinhos). Valores baixos tendem a ajustar mais ao ruído; valores maiores suavizam a decisão.

```{r}
# Classification using KNN

# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

```{r}
iris <- datasets::iris
head(iris)
```

```{r}
# extracting the levels for the dataset
slevels <- levels(iris$Species)
slevels
```


```{r}
# Building samples (training and testing) using random sampling
set.seed(1)
sr <- sample_random()
sr <- train_test(sr, iris)
iris_train <- sr$train
iris_test <- sr$test
```

```{r}

tbl <- rbind(table(iris[,"Species"]), 
             table(iris_train[,"Species"]), 
             table(iris_test[,"Species"]))
rownames(tbl) <- c("dataset", "training", "test")
head(tbl)
```

```{r}
# Model training
model <- cla_knn("Species", slevels, k=1)
model <- fit(model, iris_train)

```

```{r}
# Checking model adjustment
train_prediction <- predict(model, iris_train)

# Model evaluation
iris_train_predictand <- adjust_class_label(iris_train[,"Species"])
train_eval <- evaluate(model, iris_train_predictand, train_prediction)
print(train_eval$metrics)
```


```{r}
# Model testing
test_prediction <- predict(model, iris_test)

iris_test_predictand <- adjust_class_label(iris_test[,"Species"])

# Evaluating # setosa as primary class
test_eval <- evaluate(model, iris_test_predictand, test_prediction)
print(test_eval$metrics)
```

