About the transformation
- `categ_mapping`: converts a categorical column into binary variables (one‑hot). Can use n columns or n-1 columns.

```{r}
# Categorical mapping
# A categorical attribute with $n$ distinct values can be mapped into $n$ binary (one‑hot) attributes.

# It is also possible to map into $n-1$ binary attributes: the case where all binary attributes are zero represents the last categorical value (not explicit in columns).

# installation 
#install.packages("daltoolbox")

# loading DAL
library(daltoolbox)
```

Apply one-hot mapping to the `Species` column in a data frame.
```{r}
# dataset for the example 

iris <- datasets::iris
head(iris)
```

```{r}
# creating the categorical mapping

cm <- categ_mapping("Species")
iris_cm <- transform(cm, iris)
print(head(iris_cm))
```

```{r}
# creating the categorical mapping
# It can be done from a single column, but it must be a data frame

diris <- iris[,"Species", drop=FALSE]
head(diris)
```

```{r}
iris_cm <- transform(cm, diris)
print(head(iris_cm))
```

References
- Bishop, C. M. (2006). Pattern Recognition and Machine Learning. Springer. (1-of-K/one-hot encoding)

