```{r}
# Mapeamento categórico
# Um atributo categórico com $n$ valores distintos pode ser mapeado em $n$ atributos binários (one‑hot).

# Também é possível mapear para $n-1$ atributos binários: o caso em que todos os atributos binários são zero representa o último valor categórico (não explícito nas colunas).

Sobre a transformação
- `categ_mapping`: converte uma coluna categórica em variáveis binárias (one‑hot). Pode usar codificação com n colunas ou n−1 colunas.

# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox)
```

Aplicando mapeamento one-hot para a coluna `Species` em um data frame.
```{r}
# conjunto de dados para o exemplo 

iris <- datasets::iris
head(iris)
```

```{r}
# criando o mapeamento categórico

cm <- categ_mapping("Species")
iris_cm <- transform(cm, iris)
print(head(iris_cm))
```

Aplicando o mesmo mapeamento para um data frame com única coluna categórica.
```{r}
# criando o mapeamento categórico
# Pode ser feito a partir de uma única coluna, mas precisa ser um data frame

diris <- iris[,"Species", drop=FALSE]
head(diris)
```

```{r}
iris_cm <- transform(cm, diris)
print(head(iris_cm))
```
