```{r}
# installation 
#install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

```{r}
# Discretization & smoothing
# Discretization is the process of transferring continuous functions, models, variables, and equations into discrete counterparts. 

# Smoothing is a technique that creates an approximating function that attempts to capture important patterns in the data while leaving out noise or other fine-scale structures/rapid phenomena.

# An important part of the discretization/smoothing is to set up bins for proceeding the approximation.

# general function to evaluate different smoothing technique

iris <- datasets::iris
head(iris)
```

```{r}
# smoothing using regular interval
obj <- smoothing_inter(n = 2)  
obj <- fit(obj, iris$Sepal.Length)
sl.bi <- transform(obj, iris$Sepal.Length)
print(table(sl.bi))
obj$interval
```

```{r}
entro <- evaluate(obj, as.factor(names(sl.bi)), iris$Species)
print(entro$entropy)
```

```{r}
# Optimizing the number of binnings

opt_obj <- smoothing_inter(n=1:20)
obj <- fit(opt_obj, iris$Sepal.Length)
obj$n
```

```{r}
obj <- fit(obj, iris$Sepal.Length)
sl.bi <- transform(obj, iris$Sepal.Length)
print(table(sl.bi))
```

