```{r}
# NA and Outlier analysis

Sobre a transformação
- `outliers_gaussian`: marca como outliers valores além de média ± 3 desvios padrão, assumindo distribuição aproximadamente normal.

# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

Removendo outliers pela regra de 3 sigmas e inspecionando.
```{r}
# Outlier removal using gaussian
# The following class uses box-plot definition for outliers.

# An outlier is a value that is below than $\overline{x} - 3 \sigma_x$ or higher than $\overline{x} + 3 \sigma_x}$.

# The class remove outliers for numeric attributes. 

# removing outliers of a data frame

# code for outlier removal
out_obj <- outliers_gaussian() # class for outlier analysis
out_obj <- fit(out_obj, iris) # computing boundaries
iris.clean <- transform(out_obj, iris) # returning cleaned dataset

# inspection of cleaned dataset
head(iris.clean)
nrow(iris.clean)
```

Listando observações identificadas como outliers.
```{r}
# Visualizing the actual outliers

idx <- attr(iris.clean, "idx")
print(table(idx))
iris.outliers <- iris[idx,]
head(iris.outliers)
```
