Sobre o método
- `reg_svm`: Support Vector Regression (SVR). Modela uma função com margem insensível a erros até `epsilon` e penaliza violações via `cost`.
- Hiperparâmetros: `epsilon`, `cost` e `kernel` (se aplicável).

```{r}
# Regression SVM

# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

```{r}
# Dataset for regression analysis

library(MASS)
data(Boston)
print(t(sapply(Boston, class)))
head(Boston)
```

```{r}
# for performance issues, you can use matrix
Boston <- as.matrix(Boston)
```

```{r}
# preparing dataset for random sampling

set.seed(1)
sr <- sample_random()
sr <- train_test(sr, Boston)
boston_train <- sr$train
boston_test <- sr$test
```

```{r}
# Training

model <- reg_svm("medv", epsilon=0.2,cost=40.000)
model <- fit(model, boston_train)
```

```{r}
# Model adjustment

train_prediction <- predict(model, boston_train)
boston_train_predictand <- boston_train[,"medv"]
train_eval <- evaluate(model, boston_train_predictand, train_prediction)
print(train_eval$metrics)
```

```{r}
# Test

test_prediction <- predict(model, boston_test)
boston_test_predictand <- boston_test[,"medv"]
test_eval <- evaluate(model, boston_test_predictand, test_prediction)
print(test_eval$metrics)
```

