# Regression Random Forest

Sobre o método
- `reg_rf`: Random Forest para regressão. Média de muitas árvores de decisão treinadas com amostragens aleatórias; tende a reduzir variância.
- Hiperparâmetros: `mtry` (nº de variáveis por divisão), `ntree` (nº de árvores).

```{r}
# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

# Dataset for regression analysis

```{r}
library(MASS)
data(Boston)
print(t(sapply(Boston, class)))
head(Boston)
```

```{r}
# for performance issues, you can use matrix
Boston <- as.matrix(Boston)
```

# Building samples (training and testing)

```{r}
# preparing dataset for random sampling
set.seed(1)
sr <- sample_random()
sr <- train_test(sr, Boston)
boston_train <- sr$train
boston_test <- sr$test
```

# Training

```{r}
model <- reg_rf("medv", mtry=7,ntree=30)
model <- fit(model, boston_train)
```

# Model adjustment

```{r}
train_prediction <- predict(model, boston_train)
boston_train_predictand <- boston_train[,"medv"]
train_eval <- evaluate(model, boston_train_predictand, train_prediction)
print(train_eval$metrics)
```

# Test

```{r}
test_prediction <- predict(model, boston_test)
boston_test_predictand <- boston_test[,"medv"]
test_eval <- evaluate(model, boston_test_predictand, test_prediction)
print(test_eval$metrics)
```

