---
title: An R Markdown document converted from "Rmd/graphics/grf_bar.ipynb"
output: html_document
---

```{r}
# DAL ToolBox
# version 1.1.727

source("https://raw.githubusercontent.com/cefet-rj-dal/daltoolbox/main/jupyter.R")

#loading DAL
load_library("daltoolbox") 
```

```{r}
load_library("RColorBrewer")
load_library("ggplot2")

colors <- brewer.pal(4, 'Set1')

# setting the font size for all charts
font <- theme(text = element_text(size=16))
```

```{r}
#iris dataset for the example
head(iris)
```

```{r}
load_library("dplyr")
data <- iris |> group_by(Species) |> summarize(Sepal.Length=mean(Sepal.Length))
head(data)
```

## Bar graph

A bar graph is used to presents categorical data with rectangular bars with heights or lengths proportional to the values that they represent. 

More information: https://en.wikipedia.org/wiki/Bar_chart

```{r}
grf <- plot_bar(data, colors=colors[1]) + font
plot(grf)
```

```{r}
# Sometimes the bars can be plotted vertically. Use function coord_flip() for that.
grf <- grf + coord_flip()
plot(grf)
```

```{r}
# Bar graph with one color for each species
grf <- plot_bar(data, colors=colors[1:3]) + font
plot(grf)
```

