Sobre o gráfico
- Barras empilhadas: mostra a composição de cada categoria somando grupos; útil para proporções acumuladas.

Preparação do ambiente gráfico.
```{r}
# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

```{r}
library(ggplot2)
library(RColorBrewer)

# color palette
colors <- brewer.pal(4, 'Set1')

# setting the font size for all charts
font <- theme(text = element_text(size=16))
```

Dados agregados por espécie para duas métricas.
```{r}
# iris dataset for the example
head(iris)
```

```{r}
library(dplyr)

data <- iris |> group_by(Species) |> summarize(Sepal.Length=mean(Sepal.Length), Sepal.Width=mean(Sepal.Width))
head(data)
```

Construindo gráfico empilhado e ajustando rótulos do eixo X.
```{r}
# Stacked-bar

# Stacked bar charts are used to organize data into groups for each category.

# A stacked bar chart stacks bars that represent different groups on top of each other. The height of the resulting bar shows the combined result of the groups. 

# More information: https://en.wikipedia.org/wiki/Bar_chart# Grouped_or_stacked

grf <- plot_stackedbar(data, colors=colors[1:2]) + font
grf <- grf + theme(axis.text.x = element_text(angle=90, hjust=1))
plot(grf)
```
