---
title: An R Markdown document converted from "Rmd/graphics/grf_save_jpg.ipynb"
output: html_document
---

```{r}
# DAL ToolBox
# version 1.1.727

source("https://raw.githubusercontent.com/cefet-rj-dal/daltoolbox/main/jupyter.R")

#loading DAL
load_library("daltoolbox") 
```

```{r}
load_library("ggplot2")
load_library("RColorBrewer")

#color palette
colors <- brewer.pal(4, 'Set1')

# setting the font size for all charts
font <- theme(text = element_text(size=16))
```

#### Synthetic time series

```{r}
x <- seq(0, 10, 0.25)
serie <- data.frame(x, sin=sin(x), cosine=cos(x)+5)
head(serie)
```

## Series plot

A series plot is a type of chart that displays information as a series of data points connected by straight line segments. 

It is similar to a scatter plot except that their x-axis value orders the measurement points.

More information: https://en.wikipedia.org/wiki/Line_chart

```{r}
grf <- plot_series(serie, colors=colors[1:2]) + font
plot(grf)
```

```{r}
  jpeg("series.jpg", width = 640, height = 480)
  plot(grf)
  dev.off()
```

```{r}
ggsave("series.png", width = 5, height = 4, units = "cm")
```

