About the chart
- Bars with error bars: add uncertainty/variability (e.g., standard deviation) to bars using `geom_errorbar()`.

```{r}
# installation 
#install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

Graphics environment setup.
```{r}
library(ggplot2)
library(RColorBrewer)

# color palette
colors <- brewer.pal(4, 'Set1')

# setting the font size for all charts
font <- theme(text = element_text(size=16))
```

Aggregated data: mean and standard deviation by species.
```{r}
# iris dataset for the example
head(iris)
```

```{r}
library(dplyr)
data <- iris |> group_by(Species) |> summarize(mean=mean(Sepal.Length), sd=sd(Sepal.Length))
head(data)
```


Build bars and add `geom_errorbar`.
```{r}
# Bar graph with error bars
# When bar graphs present an average behavior, it is possible to plot a dispersion around it using an error bar.
# The error bar is added using $geom\_errorbar()$ function to a previously defined bar graph. 

grf <- plot_bar(data, colors=colors[1], alpha=1) + font
grf <- grf + geom_errorbar(aes(x=Species, ymin=mean-sd, ymax=mean+sd), 
                           width=0.2, colour="darkred", alpha=0.8, size=1.1) 
plot(grf)
```

References
- Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer. (geom_errorbar)
