Sobre o gráfico
- Radar: exibe múltiplas variáveis numéricas em eixos radiais a partir de uma origem comum; útil para perfis comparativos.

Preparação do ambiente gráfico.
```{r}
# installation 
install.packages("daltoolbox")

# loading DAL
library(daltoolbox) 
```

```{r}
library(ggplot2)
library(RColorBrewer)

# color palette
colors <- brewer.pal(4, 'Set1')

# setting the font size for all charts
font <- theme(text = element_text(size=16))
```

Média por variável numérica e montagem do formato requerido para radar.
```{r}
# iris dataset for the example
head(iris)
```

```{r}
library(dplyr)

data <- iris |> dplyr::select(-Species) 
data <- sapply(data, mean)
data <- data.frame(name = names(data), value = data) |> dplyr::arrange(name)

head(data)
```

```{r}

# Radar plot

# A radar chart is a graphical method of displaying multivariate data containing three or more quantitative variables represented on axes starting from the same point. 

# More information: https://en.wikipedia.org/wiki/Radar_chart

grf <- plot_radar(data, colors=colors[1]) + font
grf <- grf + ylim(0, NA)
plot(grf)
```
